name: untitled5
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: 2.0.16
  go_router: 14.6.1
  provider: 6.1.2
  flutter_bloc: 8.1.6
  dio: any
  retrofit: any
  json_annotation: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  retrofit_generator: any
  json_serializable: any
  build_runner: any


flutter:

  uses-material-design: true

  assets:
    - res/drawables/
    - res/fonts/
    - res/svg/

  fonts:
    - family: AppIcons
      fonts:
        - asset: res/fonts/app_icons.ttf